// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrafficMonitor.Common;

#nullable disable

namespace TrafficMonitor.Common.Migrations
{
    [DbContext(typeof(TrafficMonitorDataContext))]
    [Migration("20240907063810_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TrafficMonitor.Common.Models.EagleBot", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Timestamp")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.ToTable("EagleBot");
                });

            modelBuilder.Entity("TrafficMonitor.Common.Models.TrafficData", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Direction")
                        .HasColumnType("int");

                    b.Property<Guid>("EagleBotId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("FlowRate")
                        .HasColumnType("float");

                    b.Property<string>("RoadName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Timestamp")
                        .HasColumnType("varbinary(max)");

                    b.Property<double?>("VehicleSpeed")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("EagleBotId");

                    b.ToTable("TrafficData");
                });

            modelBuilder.Entity("TrafficMonitor.Common.Models.TrafficData", b =>
                {
                    b.HasOne("TrafficMonitor.Common.Models.EagleBot", "EagleBot")
                        .WithMany("TrafficData")
                        .HasForeignKey("EagleBotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Coordinate", "Location", b1 =>
                        {
                            b1.Property<Guid>("TrafficDataId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double>("Latitude")
                                .HasColumnType("float");

                            b1.Property<double>("Longitude")
                                .HasColumnType("float");

                            b1.HasKey("TrafficDataId");

                            b1.ToTable("TrafficData");

                            b1.WithOwner()
                                .HasForeignKey("TrafficDataId");
                        });

                    b.Navigation("EagleBot");

                    b.Navigation("Location")
                        .IsRequired();
                });

            modelBuilder.Entity("TrafficMonitor.Common.Models.EagleBot", b =>
                {
                    b.Navigation("TrafficData");
                });
#pragma warning restore 612, 618
        }
    }
}
